name: "New track request"
description: Create a request to add a new track to the iceberg
title: "[NEW TRACK] - Enter a descriptive title"
body:
  - type: dropdown
    id: site
    attributes:
      label: "Site"
      description: Where did you find the track?
      multiple: false
      options:
        - Bandcamp
        - SoundCloud
    validations:
      required: true

  - type: dropdown
    id: level
    attributes:
      label: "Level"
      description: At which level does this track belong?
      multiple: false
      options:
        - Surface Waters
        - Twilight Zone
        - Midnight Zone
        - Abyssal Plain
        - Hadal Zone
    validations:
      required: false

  - type: input
    id: band_name
    attributes:
      label: "Band Name"
    validations:
      required: true

  - type: input
    id: track_name
    attributes:
      label: "Track Name"
    validations:
      required: true